CREATE TABLE directors (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    first_name TEXT,
    last_name TEXT,
    birth_year INTEGER,
    photo TEXT,
    bio TEXT
);

INSERT INTO directors (first_name, last_name, birth_year, photo, bio) VALUES ('David', 'Fincher', 1962, 'https://m.media-amazon.com/images/M/MV5BMTc1NDkwMTQ2MF5BMl5BanBnXkFtZTcwMzY0ODkyMg@@._V1_UX214_CR0,0,214,317_AL_.jpg', 'David Fincher was born in 1962 in Denver, Colorado, and was raised in Marin County, California. When he was 18 years old he went to work for John Korty at Korty Films in Mill Valley. He subsequently worked at ILM (Industrial Light and Magic) from 1981-1983. Fincher left ILM to direct TV commercials and music videos after signing with N. Lee Lacy in Hollywood. He went on to found Propaganda in 1987 with fellow directors Dominic Sena, Greg Gold and Nigel Dick. Fincher has directed TV commercials for clients that include Nike, Coca-Cola, Budweiser, Heineken, Pepsi, Levis, Converse, AT&T and Chanel. He has directed music videos for Madonna, Sting, The Rolling Stones, Michael Jackson, Aerosmith, George Michael, Iggy Pop, The Wallflowers, Billy Idol, Steve Winwood, The Motels and, most recently, A Perfect Circle. \n\n As a film director, he has achieved huge success with Seven (1995), Fight Club (1999) and, Panic Room (2002).' );

INSERT INTO directors (first_name, last_name, birth_year, photo, bio) VALUES ('Matt', 'Reeves', 1966, 'https://m.media-amazon.com/images/M/MV5BYmM5NTA4ZGMtMGJhYy00YzlhLThlM2QtZjFjY2Y5YmJjOTE2XkEyXkFqcGdeQXVyNzg5MzIyOA@@._V1_UX214_CR0,0,214,317_AL_.jpg', 'Matthew George "Matt" Reeves was born April 27, 1966 in Rockville Center, New York, USA and is a writer, director and producer. Reeves began making movies at age eight, directing friends and using a wind-up camera. He befriended filmmaker J.J. Abrams when both were 13 years old and a public-access television cable channel, Z Channel, aired their short films. When Reeves and Abrams were 15 or 16 years old, Steven Spielberg hired them to transfer some of his own Super 8 films to videotape. Reeves attended the University of Southern California and there, between 1991 and 1992, he produced an award-winning student film, Mr. Petrified Forest, which helped him acquire an agent. He also co-wrote a script that eventually became Under Siege 2: Dark Territory (1995). After graduating, he co-wrote The Pallbearer (1996), which became his directorial debut./n/nReeves and J.J. Abrams co-created the TV series Felicity (1998), for which Reeves directed several episodes, including the pilot. He has also helmed occasional episodes of other television series. He co-wrote The Yards (2000) with director James Gray, which he also co-produced. In 2008, Reeves directed the monster science fiction film Cloverfield (2008), which Abrams produced. Reeves later served as an executive producer on 10 Cloverfield Lane (2016) and The Cloverfield Paradox (2018). He wrote and directed the fantasy-horror film Let Me In (2010), a remake of the Swedish film Let the Right One In (2008). Reeves directed the science fiction films Dawn of the Planet of the Apes (2014) and later the sequel, War for the Planet of the Apes (2017). He served as an executive producer on the Amazon original series Tales from the Loop (2020).');